#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'SensorReportMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 12

# The Active Message type associated with this message.
AM_TYPE = 2

class SensorReportMsg(tinyos.message.Message.Message):
    # Create a new SensorReportMsg of size 12.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=12):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <SensorReportMsg> \n"
        try:
            s += "  [counter=0x%x]\n" % (self.get_counter())
        except:
            pass
        try:
            s += "  [moteId=0x%x]\n" % (self.get_moteId())
        except:
            pass
        try:
            s += "  [temperatureValue=0x%x]\n" % (self.get_temperatureValue())
        except:
            pass
        try:
            s += "  [humidityValue=0x%x]\n" % (self.get_humidityValue())
        except:
            pass
        try:
            s += "  [photoLightValue=0x%x]\n" % (self.get_photoLightValue())
        except:
            pass
        try:
            s += "  [fullLightValue=0x%x]\n" % (self.get_fullLightValue())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: counter
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'counter' is signed (False).
    #
    def isSigned_counter(self):
        return False
    
    #
    # Return whether the field 'counter' is an array (False).
    #
    def isArray_counter(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'counter'
    #
    def get_counter(self):
        return self.getUIntElement(self.offsetBits_counter(), 16, 1)
    
    #
    # Set the value of the field 'counter'
    #
    def set_counter(self, value):
        self.setUIntElement(self.offsetBits_counter(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'counter'
    #
    def size_counter(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'counter'
    #
    def sizeBits_counter(self):
        return 16
    
    #
    # Accessor methods for field: moteId
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'moteId' is signed (False).
    #
    def isSigned_moteId(self):
        return False
    
    #
    # Return whether the field 'moteId' is an array (False).
    #
    def isArray_moteId(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'moteId'
    #
    def offset_moteId(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'moteId'
    #
    def offsetBits_moteId(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'moteId'
    #
    def get_moteId(self):
        return self.getUIntElement(self.offsetBits_moteId(), 16, 1)
    
    #
    # Set the value of the field 'moteId'
    #
    def set_moteId(self, value):
        self.setUIntElement(self.offsetBits_moteId(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'moteId'
    #
    def size_moteId(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'moteId'
    #
    def sizeBits_moteId(self):
        return 16
    
    #
    # Accessor methods for field: temperatureValue
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'temperatureValue' is signed (False).
    #
    def isSigned_temperatureValue(self):
        return False
    
    #
    # Return whether the field 'temperatureValue' is an array (False).
    #
    def isArray_temperatureValue(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'temperatureValue'
    #
    def offset_temperatureValue(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'temperatureValue'
    #
    def offsetBits_temperatureValue(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'temperatureValue'
    #
    def get_temperatureValue(self):
        return self.getUIntElement(self.offsetBits_temperatureValue(), 16, 1)
    
    #
    # Set the value of the field 'temperatureValue'
    #
    def set_temperatureValue(self, value):
        self.setUIntElement(self.offsetBits_temperatureValue(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'temperatureValue'
    #
    def size_temperatureValue(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'temperatureValue'
    #
    def sizeBits_temperatureValue(self):
        return 16
    
    #
    # Accessor methods for field: humidityValue
    #   Field type: int
    #   Offset (bits): 48
    #   Size (bits): 16
    #

    #
    # Return whether the field 'humidityValue' is signed (False).
    #
    def isSigned_humidityValue(self):
        return False
    
    #
    # Return whether the field 'humidityValue' is an array (False).
    #
    def isArray_humidityValue(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'humidityValue'
    #
    def offset_humidityValue(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'humidityValue'
    #
    def offsetBits_humidityValue(self):
        return 48
    
    #
    # Return the value (as a int) of the field 'humidityValue'
    #
    def get_humidityValue(self):
        return self.getUIntElement(self.offsetBits_humidityValue(), 16, 1)
    
    #
    # Set the value of the field 'humidityValue'
    #
    def set_humidityValue(self, value):
        self.setUIntElement(self.offsetBits_humidityValue(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'humidityValue'
    #
    def size_humidityValue(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'humidityValue'
    #
    def sizeBits_humidityValue(self):
        return 16
    
    #
    # Accessor methods for field: photoLightValue
    #   Field type: int
    #   Offset (bits): 64
    #   Size (bits): 16
    #

    #
    # Return whether the field 'photoLightValue' is signed (False).
    #
    def isSigned_photoLightValue(self):
        return False
    
    #
    # Return whether the field 'photoLightValue' is an array (False).
    #
    def isArray_photoLightValue(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'photoLightValue'
    #
    def offset_photoLightValue(self):
        return (64 / 8)
    
    #
    # Return the offset (in bits) of the field 'photoLightValue'
    #
    def offsetBits_photoLightValue(self):
        return 64
    
    #
    # Return the value (as a int) of the field 'photoLightValue'
    #
    def get_photoLightValue(self):
        return self.getUIntElement(self.offsetBits_photoLightValue(), 16, 1)
    
    #
    # Set the value of the field 'photoLightValue'
    #
    def set_photoLightValue(self, value):
        self.setUIntElement(self.offsetBits_photoLightValue(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'photoLightValue'
    #
    def size_photoLightValue(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'photoLightValue'
    #
    def sizeBits_photoLightValue(self):
        return 16
    
    #
    # Accessor methods for field: fullLightValue
    #   Field type: int
    #   Offset (bits): 80
    #   Size (bits): 16
    #

    #
    # Return whether the field 'fullLightValue' is signed (False).
    #
    def isSigned_fullLightValue(self):
        return False
    
    #
    # Return whether the field 'fullLightValue' is an array (False).
    #
    def isArray_fullLightValue(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'fullLightValue'
    #
    def offset_fullLightValue(self):
        return (80 / 8)
    
    #
    # Return the offset (in bits) of the field 'fullLightValue'
    #
    def offsetBits_fullLightValue(self):
        return 80
    
    #
    # Return the value (as a int) of the field 'fullLightValue'
    #
    def get_fullLightValue(self):
        return self.getUIntElement(self.offsetBits_fullLightValue(), 16, 1)
    
    #
    # Set the value of the field 'fullLightValue'
    #
    def set_fullLightValue(self, value):
        self.setUIntElement(self.offsetBits_fullLightValue(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'fullLightValue'
    #
    def size_fullLightValue(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'fullLightValue'
    #
    def sizeBits_fullLightValue(self):
        return 16
    
