/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SensorRequestMsg'
 * message type.
 */

public class SensorRequestMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 10;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new SensorRequestMsg of size 10. */
    public SensorRequestMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SensorRequestMsg of the given data_length. */
    public SensorRequestMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorRequestMsg with the given data_length
     * and base offset.
     */
    public SensorRequestMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorRequestMsg using the given byte array
     * as backing store.
     */
    public SensorRequestMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorRequestMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SensorRequestMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorRequestMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SensorRequestMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorRequestMsg embedded in the given message
     * at the given base offset.
     */
    public SensorRequestMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorRequestMsg embedded in the given message
     * at the given base offset and length.
     */
    public SensorRequestMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SensorRequestMsg> \n";
      try {
        s += "  [counter=0x"+Long.toHexString(get_counter())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [moteId=0x"+Long.toHexString(get_moteId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sensorId=0x"+Long.toHexString(get_sensorId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [period=0x"+Long.toHexString(get_period())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [avg=0x"+Long.toHexString(get_avg())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (false).
     */
    public static boolean isArray_counter() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'counter'
     */
    public int get_counter() {
        return (int)getUIntBEElement(offsetBits_counter(), 16);
    }

    /**
     * Set the value of the field 'counter'
     */
    public void set_counter(int value) {
        setUIntBEElement(offsetBits_counter(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'counter'
     */
    public static int size_counter() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'counter'
     */
    public static int sizeBits_counter() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: moteId
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'moteId' is signed (false).
     */
    public static boolean isSigned_moteId() {
        return false;
    }

    /**
     * Return whether the field 'moteId' is an array (false).
     */
    public static boolean isArray_moteId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'moteId'
     */
    public static int offset_moteId() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'moteId'
     */
    public static int offsetBits_moteId() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'moteId'
     */
    public int get_moteId() {
        return (int)getUIntBEElement(offsetBits_moteId(), 16);
    }

    /**
     * Set the value of the field 'moteId'
     */
    public void set_moteId(int value) {
        setUIntBEElement(offsetBits_moteId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'moteId'
     */
    public static int size_moteId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'moteId'
     */
    public static int sizeBits_moteId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sensorId
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sensorId' is signed (false).
     */
    public static boolean isSigned_sensorId() {
        return false;
    }

    /**
     * Return whether the field 'sensorId' is an array (false).
     */
    public static boolean isArray_sensorId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sensorId'
     */
    public static int offset_sensorId() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sensorId'
     */
    public static int offsetBits_sensorId() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'sensorId'
     */
    public int get_sensorId() {
        return (int)getUIntBEElement(offsetBits_sensorId(), 16);
    }

    /**
     * Set the value of the field 'sensorId'
     */
    public void set_sensorId(int value) {
        setUIntBEElement(offsetBits_sensorId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sensorId'
     */
    public static int size_sensorId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sensorId'
     */
    public static int sizeBits_sensorId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: period
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'period' is signed (false).
     */
    public static boolean isSigned_period() {
        return false;
    }

    /**
     * Return whether the field 'period' is an array (false).
     */
    public static boolean isArray_period() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'period'
     */
    public static int offset_period() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'period'
     */
    public static int offsetBits_period() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'period'
     */
    public int get_period() {
        return (int)getUIntBEElement(offsetBits_period(), 16);
    }

    /**
     * Set the value of the field 'period'
     */
    public void set_period(int value) {
        setUIntBEElement(offsetBits_period(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'period'
     */
    public static int size_period() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'period'
     */
    public static int sizeBits_period() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: avg
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'avg' is signed (false).
     */
    public static boolean isSigned_avg() {
        return false;
    }

    /**
     * Return whether the field 'avg' is an array (false).
     */
    public static boolean isArray_avg() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'avg'
     */
    public static int offset_avg() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'avg'
     */
    public static int offsetBits_avg() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'avg'
     */
    public int get_avg() {
        return (int)getUIntBEElement(offsetBits_avg(), 16);
    }

    /**
     * Set the value of the field 'avg'
     */
    public void set_avg(int value) {
        setUIntBEElement(offsetBits_avg(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'avg'
     */
    public static int size_avg() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'avg'
     */
    public static int sizeBits_avg() {
        return 16;
    }

}
