#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'SensorRequestMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 10

# The Active Message type associated with this message.
AM_TYPE = 1

class SensorRequestMsg(tinyos.message.Message.Message):
    # Create a new SensorRequestMsg of size 10.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=10):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <SensorRequestMsg> \n"
        try:
            s += "  [counter=0x%x]\n" % (self.get_counter())
        except:
            pass
        try:
            s += "  [moteId=0x%x]\n" % (self.get_moteId())
        except:
            pass
        try:
            s += "  [sensorId=0x%x]\n" % (self.get_sensorId())
        except:
            pass
        try:
            s += "  [period=0x%x]\n" % (self.get_period())
        except:
            pass
        try:
            s += "  [avg=0x%x]\n" % (self.get_avg())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: counter
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'counter' is signed (False).
    #
    def isSigned_counter(self):
        return False
    
    #
    # Return whether the field 'counter' is an array (False).
    #
    def isArray_counter(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'counter'
    #
    def get_counter(self):
        return self.getUIntElement(self.offsetBits_counter(), 16, 1)
    
    #
    # Set the value of the field 'counter'
    #
    def set_counter(self, value):
        self.setUIntElement(self.offsetBits_counter(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'counter'
    #
    def size_counter(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'counter'
    #
    def sizeBits_counter(self):
        return 16
    
    #
    # Accessor methods for field: moteId
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'moteId' is signed (False).
    #
    def isSigned_moteId(self):
        return False
    
    #
    # Return whether the field 'moteId' is an array (False).
    #
    def isArray_moteId(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'moteId'
    #
    def offset_moteId(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'moteId'
    #
    def offsetBits_moteId(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'moteId'
    #
    def get_moteId(self):
        return self.getUIntElement(self.offsetBits_moteId(), 16, 1)
    
    #
    # Set the value of the field 'moteId'
    #
    def set_moteId(self, value):
        self.setUIntElement(self.offsetBits_moteId(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'moteId'
    #
    def size_moteId(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'moteId'
    #
    def sizeBits_moteId(self):
        return 16
    
    #
    # Accessor methods for field: sensorId
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'sensorId' is signed (False).
    #
    def isSigned_sensorId(self):
        return False
    
    #
    # Return whether the field 'sensorId' is an array (False).
    #
    def isArray_sensorId(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sensorId'
    #
    def offset_sensorId(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'sensorId'
    #
    def offsetBits_sensorId(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'sensorId'
    #
    def get_sensorId(self):
        return self.getUIntElement(self.offsetBits_sensorId(), 16, 1)
    
    #
    # Set the value of the field 'sensorId'
    #
    def set_sensorId(self, value):
        self.setUIntElement(self.offsetBits_sensorId(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sensorId'
    #
    def size_sensorId(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'sensorId'
    #
    def sizeBits_sensorId(self):
        return 16
    
    #
    # Accessor methods for field: period
    #   Field type: int
    #   Offset (bits): 48
    #   Size (bits): 16
    #

    #
    # Return whether the field 'period' is signed (False).
    #
    def isSigned_period(self):
        return False
    
    #
    # Return whether the field 'period' is an array (False).
    #
    def isArray_period(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'period'
    #
    def offset_period(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'period'
    #
    def offsetBits_period(self):
        return 48
    
    #
    # Return the value (as a int) of the field 'period'
    #
    def get_period(self):
        return self.getUIntElement(self.offsetBits_period(), 16, 1)
    
    #
    # Set the value of the field 'period'
    #
    def set_period(self, value):
        self.setUIntElement(self.offsetBits_period(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'period'
    #
    def size_period(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'period'
    #
    def sizeBits_period(self):
        return 16
    
    #
    # Accessor methods for field: avg
    #   Field type: int
    #   Offset (bits): 64
    #   Size (bits): 16
    #

    #
    # Return whether the field 'avg' is signed (False).
    #
    def isSigned_avg(self):
        return False
    
    #
    # Return whether the field 'avg' is an array (False).
    #
    def isArray_avg(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'avg'
    #
    def offset_avg(self):
        return (64 / 8)
    
    #
    # Return the offset (in bits) of the field 'avg'
    #
    def offsetBits_avg(self):
        return 64
    
    #
    # Return the value (as a int) of the field 'avg'
    #
    def get_avg(self):
        return self.getUIntElement(self.offsetBits_avg(), 16, 1)
    
    #
    # Set the value of the field 'avg'
    #
    def set_avg(self, value):
        self.setUIntElement(self.offsetBits_avg(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'avg'
    #
    def size_avg(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'avg'
    #
    def sizeBits_avg(self):
        return 16
    
